global:
  name: DLT Landscape
  short_name: DLTLandscape
  repo: dltlanscape/dlt-landscape
  website: https://dltlandscape.org
  short_domain: https://dltlandscape.org
  company_url: https://dltlandscape.org
  email: info@dltlandscape.org
  # self: https://www.crunchbase.com/organization/
  # slack_channel:
  membership: Members
  meta:
    title: https://dltlandscape.org
    description: Filter and sort by GitHub stars, funding, commits, contributors, hq location, and tweets
    # fb_admin: username
    twitter: 'dltlandscape'
    # google_site_verification: 
    # ms_validate: 
  flags:
    companies: false
twitter:
  search: dltlandscape.org
  url: https://dltlandscape.org
  text: DLT Landscape
relation:
  label: Type
  url: dltlandscape.org
  values:
    - id: type
      label: Type
      children:
        - id: company-child
          label: Company
          tag: Company
          color: '#00cbff'
          big_picture_order: 1
          big_picture_color: rgb(24,54,114)
        - id: project-child
          label: Project
          tag: Project
          color: '#00cbff'
          big_picture_order: 1
          big_picture_color: rgb(24,54,114)
    - id: company
      label: Company
      tag: Company
      color: '#00cbff'
      big_picture_order: 1
      big_picture_color: rgb(24,54,114)
    - id: project
      label: Project
      tag: Project
      color: '#00cbff'
      big_picture_order: 1
      big_picture_color: rgb(24,54,114)
    - id: false
      label: NA
      url: 'no'
membership:
  Platinum:
    name: Platinum
    label: Platinum Member
    funding: Platinum
    is_large: true
  Gold:
    name: Gold
    label: Gold Member
    funding: Gold
    is_large: true
  Silver:
    name: Silver
    label: Silver Member
    funding: Silver
  linux_foundation:
    name: LF
    label: Project
    funding: Linux Foundation
    crunchbase_and_children: https://www.crunchbase.com/organization/linux-foundation
home:
  header: >
    <h1>DLT Landscape</h1> The DLT landscape (<a target="_blank" href="images/landscape.png">png</a>, <a
    target="_blank" href="images/landscape.pdf">pdf</a>) is dynamically generated below. It is modeled after the <a href="http://landscape.cncf.io">CNCF
    landscape</a> and based on the same open source code.
  footer: |
    Footer text
ads:
  - url: https://events.linuxfoundation.org/kubecon-cloudnativecon-europe/?utm_source=dltlandscape&utm_medium=web&utm_campaign=kccnceu21
    image: /images/info1.jpg
    title: KubeCon + CloudNativeCon Europe 2021 Virtual
presets:
  - url: /format=card-mode&grouping=no&license=open-source&sort=first-commit
    label: Open source cards by age
  - url: /license=apache-license-2-0
    label: Apache-2.0 landscape
  - url: /format=card-mode&grouping=category
    label: Cards in categories
  - url: /format=card-mode&grouping=no&sort=stars
    label: Cards by stars
  - url: /format=card-mode&grouping=headquarters
    label: Group by location
  - url: /format=card-mode&grouping=no&sort=amount
    label: Cards by MCap/Funding
big_picture:
  main:
    tab_index: -1
    url: landscape
    name: Landscape
    title: DLT Landscape
    fullscreen_header: See the interactive landscape at dltlandscape.org
    elements:
      - type: VerticalCategory
        category: Platforms Management/Operations
        cols: 4
        width: 175
        height: 1360
        top: 0
        left: 0
        color: rgb(0,181,226)
      - type: HorizontalCategory
        category: Applications
        rows: 4
        width: 900
        height: 180
        top: 0
        left: 200
        color: rgb(0,181,226)
      - type: HorizontalCategory
        category: Business Tooling/Integrations
        rows: 4
        width: 900
        height: 180
        top: 200
        left: 200
        color: rgb(0,181,226)
        fit_width: false
      - type: HorizontalCategory
        category: Smart Contracts/Tokenization
        rows: 4
        width: 900
        height: 180
        top: 400
        left: 200
        color: rgb(0,181,226)
        fit_width: false
      - type: HorizontalCategory
        category: Interoperability
        rows: 4
        width: 900
        height: 180
        top: 600
        left: 200
        color: rgb(0,181,226)
        fit_width: false
      - type: HorizontalCategory
        category: Technology Intersections
        rows: 4
        width: 900
        height: 180
        top: 800
        left: 200
        color: rgb(0,134,191)
        fit_width: false
      - type: HorizontalCategory
        category: Distributed Ledgers
        rows: 4
        width: 900
        height: 180
        top: 1000
        left: 200
        color: rgb(0,181,226)
        fit_width: false
      - type: HorizontalCategory
        category: Infrastructure
        rows: 4
        width: 900
        height: 180
        top: 1200
        left: 200
        color: rgb(0,181,226)
        fit_width: false
      - type: VerticalCategory
        category: Consulting/Professional Services
        cols: 4
        width: 175
        height: 1360
        top: 0
        left: 1125
        color: rgb(0,181,226)
      - type: LandscapeInfo
        width: 430
        height: 300
        top: 1400
        left: 0
        children:
          - type: text
            text: |
              Welcome to a living segmentation of the evolving DLT market! DLT Landscape is a 
              business stack with a technology foundation. BTP has created the DLT Landscape 
              for the whole blockchain/DLT community to benefit from and contribute to. The 
              DLT Landscape is open source, curated and hosted by BTP, but independent of the company. 
            top: 65
            left: 130
            right: 20
            font_size: 11
          - type: image
            image: qr.svg
            top: 80
            left: 20
            width: 90
            height: 90
            title: QR Code
          - type: title
            title: dltlandscape.org
            top: 185
            left: 24
            font_size: 16
          - type: image
            image: left-logo.svg
            width: 120
            left: 100
            top: 20
            title: Landscape Logo
          - type: image
            image: right-logo.svg
            width: 100
            right: 20
            top: 20
            title: DLT Landscape Logo
# test:
#   header: 
#   section: 
#   logo: 